### ISSUE TITLE
In your Installation section you should document installing the SNAP version

### ISSUE THREAD

**Issue by bmullan** [sayems/lxc.resources#5]
In the future Stephane Graber has mentioned on the linuxcontainers.org LXD forum that the SNAP version of LXD will become the only version for Ubuntu.

He said that an apt-get version or repository version for other distro's could be built using source by other maintainers but that the LXD team will be focusing only on the SNAP version in the future since it can be installed on many distro's without adding a lot of additional work onto the core LXD development team.

https://discuss.linuxcontainers.org/t/lxd-snap-call-for-testing/446

> **Why a snap?**
> The snap packaging format lets us as the upstream publish a tested, blessed build of LXD and anything that it needs which can be used on a wide range of Linux distributions.
> 
> This makes it easy to get the exact same experience regardless of Linux distribution and greatly simplifies support on our end as we can reproduce bit for bit any installation.
> 
> **Moving forward, we will be phasing out our Ubuntu PPAs and then our backports to older Ubuntu releases. Both of those use cases will be transitioned over to the snap.
> 
> This will significantly reduce the amount of time we have to spend on building and testing all of those packages and the machinery used to publish them.**

**Comment by sayems** [comment]
Thanks @bmullan I will update the docs.

**Comment by sayems** [comment]
Done!
